version: '2'

services:
  rhodecode:
    image: weseek/rhodecode-ce-dockerized:4.9.0
    #links:
    #  - db
    volumes:
     - repos:/home/rhodecode/repo
    expose:
      - 8080
      - 3690
    ports:
      - 8080
      - 3690

volumes:
  repos:
